ConvertFrom-StringData -StringData @'
ActiveMountPoints                       = Active mount points detected. Performing clean-up.
InvalidWindowsInstallMedia              = "{0}" does not contain valid Windows Installation media.
ExportingMedia                          = Exporting media from "{0}"
CopyingWIM                              = Copying WIM from "{0}"
SelectWindows10Edition                  = Select the Windows 10 Edition to Optimize.
FailedToRetrieveMetadata                = Failed to retrieve necessary image metadata.
UnsupportedImageVersion                 = Unsupported Image Version: [{0}]
UnsupportedImageArch                    = Unsupported Image Architecture: [{0}]
UnsupportedImageType                    = Unsupported Image Installation Type: [{0}]
UnsupportedImageBuild                   = Unsupported Image Build: [{0}]
SupportedImageBuild                     = Supported Image Build: [{0}]
MountingImage                           = Mounting {0}
FailedMountingImage                     = Failed to Mount {0}: {1}
PreOptimizedImageHealthHealthy          = Pre-Optimization Image Health State: [Healthy]
PreOptimizedImageHealthCorrupted        = The image has been flagged for corruption. Further servicing is required before the image can be optimized.
RemovingWindowsApp                      = Removing Provisioned App Package: {0}
FailedRemovingWindowsApps               = Failed to Remove Provisioned App Packages: {0}
SystemAppsWarning                       = Do NOT remove any System Application if you are unsure of its impact on a live installation.
RemovingSystemApp                       = Removing System App: {0}
FailedRemovingSystemApp                 = Failed to Remove System App: {0}
FailedRemovingSystemApps                = Failed to Remove System Apps: {0}
RemovePackageCleanup                    = Disabling Services, Drivers and Integration Content for Removed Apps.
FailedRemovePackageCleanup              = Failed to Disable Services, Drivers and Integration Content for Removed Apps: {0}
DisablingDefenderOptionalFeature        = Disabling Optional Feature: Windows-Defender-Default-Definitions
ImportingCustomAppAssociations          = Importing Custom App Associations.
FailedImportingCustomAppAssociations    = Failed to Import Custom App Associations.
RemovingWindowsCapability               = Removing Windows Capability: {0}
FailedRemovingWindowsCapabilities       = Failed to Remove Windows Capabilities: {0}
RemovingWindowsPackage                  = Removing Windows Package: {0}
FailedRemovingWindowsPackages           = Failed to Remove Windows Packages: {0}
DisablingUnsafeOptionalFeature          = Disabling Optional Feature: {0}
DisablingOptionalFeature                = Disabling Optional Feature: {0}
FailedDisablingOptionalFeatures         = Failed to Disable Optional Features: {0}
EnablingOptionalFeature                 = Enabling Optional Feature: {0}
FailedEnablingOptionalFeatures          = Failed to Enable Optional Features: {0}
IntegratingDeveloperMode                = Integrating the Developer Mode Feature Package.
FailedIntegratingDeveloperMode          = Failed to Integrate the Developer Mode Feature Package.
IntegratingWindowsStore                 = Integrating the Windows Store Application Packages.
FailedIntegratingWindowsStore           = Failed to Integrate the Windows Store Application Packages: {0}
IntegratingMicrosoftEdge                = Integrating the Microsoft Edge Browser Application Packages.
FailedIntegratingMicrosoftEdge          = Failed to Integrate the Microsoft Edge Browser Application Packages: {0}
IntegratingWin32Calc                    = Integrating the Win32 Calculator.
FailedIntegratingWin32Calc              = Failed to Integrate the Win32 Calculator: {0}
IntegratingDataDedup                    = Integrating the Data Deduplication Packages.
FailedIntegratingDataDedup              = Failed to Integrate the Data Deduplication Packages: {0}
IntegratingDaRT10                       = Integrating Microsoft DaRT 10 and Windows {0} Debugging Tools into {1}
FailedIntegratingDaRT10                 = Failed to Integrate Microsoft DaRT 10 into {0}: {1}
ApplyingRegistrySettings                = Applying Optimized Registry Settings.
ApplyingSetupContent                    = Applying Setup Content.
ApplyingWallpaper                       = Applying Wallpaper.
ApplyingSystemLogo                      = Applying System Logo.
ApplyingLockScreen                      = Applying Lock Screen.
ImportingRegistryTemplates              = Importing Registry Templates.
ApplyingAnswerFile                      = Applying Answer File.
FailedApplyingAnswerFile                = Failed to Apply Answer File: {0}
InjectingDriverPackages                 = Injecting Driver Packages into {0}
FailedInjectingDriverPackages           = Failed to Inject Driver Packages into {0}: {1}
EnablingNetFx3                          = Enabling Windows Feature: NetFx3
FailedEnablingNetFx3                    = Failed to Enable Windows Feature: NetFx3: {0}
CleanupStartMenu                        = Cleaning-up the Start Menu Layout.
CreatingPackageSummaryLog               = Creating a Package Summary Log.
PostOptimizedImageHealthHealthy         = Post-Optimization Image Health State: [Healthy]
PostOptimizedImageHealthCorrupted       = The image has been flagged for corruption. Discarding optimizations.
SavingDismountingImage                  = Saving and Dismounting {0}
FailedSavingDismountingImage            = Failed to Save and Dismount {0}: {1}
RebuildingExportingImage                = Rebuilding and Exporting {0}
FailedRebuildingExportingImage          = Failed to Rebuild and Export {0}: {1}
SolidCompressionWarning                 = Solid compression can take quite a while. Please be patient until it completes.
RebuildingExportingCompressed           = Rebuilding and Exporting {0} using {1} compression.
FailedRebuildingExportingSolid          = Failed to Rebuild and Export {0} using {1} compression.
FailedRebuildingExportingCompressed     = Failed to Rebuild and Export {0} using {1} compression: {2}
OptimizingWindowsMedia                  = Optimizing the Windows Media File Structure.
CreatingISO                             = Creating a {0} Bootable Windows Installation Media ISO.
FinalizingOptimizations                 = Finalizing Optimizations.
OptimizationsCompleted                  = {0} completed in [{1}] minutes with [{2}] errors.
'@