ConvertFrom-StringData -StringData @'
DisableCortana                      = Disabling Cortana and Search Bar Web Connectivity.
DisableTelemetry                    = Disabling System Telemetry, Logging, Data Collecting and Advertisements.
DisableTracking                     = Disabling Windows Tracking.
DisableLocation                     = Disabling System Location Sensors.
DisableDefaultBrowserPrompt         = Disabling the Prompt to make Microsoft Edge the default browser.
DisablePassReveal                   = Disabling the Password Reveal Button.
DisableSharedExperiences            = Disabling Cross-Device Sharing and Shared Experiences.
DisableWiFiSense                    = Disabling WiFi Sense.
DisableNotifications                = Disabling Microsoft Toast and Lockscreen Notifications.
DisableAutoplayAutorun              = Disabling Connected Drive Autoplay and Autorun.
DisableFileBlocking                 = Disabling Automatic Download File Blocking.
DisableModernUISwapFile             = Disabling the Modern UI Swap File.
DisableReservedStorage              = Disabling Reserved Storage.
DisableAutoCleanup                  = Disabling the Automatic Clean-up of Downloads by Storage Sense.
DisableLogonAnimation               = Disabling the First Log-on Animation.
DisableStartupSound                 = Disabling the Windows Start-up Sound.
DisableGetMoreNotification          = Disabling the Get More out of Windows Start-up Notification.
EnableSearchIcon                    = Enabling the Search Icon on Taskbar.
EnableDriveLetterBeforeDriveName    = Enabling the Driver Letter before Drive Name.
EnableOLEDTaskbar                   = Optimizing Taskbar Icons and Transparency.
EnableLaunchToThisPC                = Enabling File Explorer Launch to This PC.
DisableJPEGQualityReduction         = Disabling Wallpaper .JPEG Quality Reduction.
DisableAcrylicBlur                  = Disabling the Sign-in Screen Acrylic Blur.
DisableShortcutText                 = Disabling the Trailing Text for Shortcuts.
EnableCMDWinXMenu                   = Enabling Command Prompt on the Win+X Quick Link Menu.
DisableEdgeShortcutPrelaunch        = Disabling Microsoft Edge Desktop Shortcut Creation and Pre-Launching.
DisableTaskbarInterestsNews         = Disabling Interests and News on Taskbar.
DisablePinnedIcons                  = Disabling Pinned Windows Store, Windows Mail and People Icons.
ReduceStartMenuDelay                = Reducing Start Menu Delay.
EnableCombineSmallIcons             = Enabling TaskBar Icon Combining with Small Icons.
DisableOpenFilePrompt               = Disabling the Open File Prompt.
EnableClassicPersonalizationPanel   = Enabling the Classic Personalization Panel.
EnableFloatingImmersiveControlPanel = Enabling the Floating Immersive Control Panel.
EnableNewStartMenu                  = Enabling the 20H2 New Start Menu.
EnableThisPCDesktop                 = Enabling This PC Desktop Icon.
RemoveEditPaintPrintContextMenu     = Removing Edit with Paint 3D and 3D Print from the Context Menu.
RestoreWindowsPhotoViewer           = Restoring Windows Photo Viewer.
RemoveUserFoldersExplorer           = Removing User Folders from Explorer.
IncreaseIconCache                   = Increasing the Icon Cache Size.
DisableStickyKeysPrompt             = Disabling the Sticky Keys Prompt.
DisableEnhancedPointerPrecision     = Disabling Enhanced Pointer Precision.
RemoveAccessShareCastContextMenu    = Removing Give Access To, Share and Cast To Device from the Context Menu.
RemoveRestorePreviousVersions       = Removing Restore Previous Versions from the Context Menu.
EnableRebootRecoveryMyPC            = Adding Reboot to Recovery to This PC.
EnableLongFilePaths                 = Enabling Long File Paths.
EnableStrongCrypto                  = Enabling Strong Cryptography for .NET Applications.
EnablePrintScreenKeyForSnipping     = Enable Printscreen key to open snipping app
'@