ConvertFrom-StringData -StringData @'
ActiveMountPoints                       = Wykryto aktywne punkty montowania. Przeprowadzanie czyszczenia.
InvalidWindowsInstallMedia              = "{0}" nie zawiera prawidłowego nośnika Instalacji Windows.
ExportingMedia                          = Eksportowanie nośnika z "{0}"
CopyingWIM                              = Kopiowanie WIM z "{0}"
SelectWindows10Edition                  = Wybierz Edycję Windows 10 aby ją Zoptymalizować.
FailedToRetrieveMetadata                = Nieudane odzyskanie wymaganych metadanych obrazu.
UnsupportedImageVersion                 = Niewspierana Wersja Obrazu: [{0}]
UnsupportedImageArch                    = Niewspierana Architektura Obrazu: [{0}]
UnsupportedImageType                    = Niewspierany Typ Instalacji Obrazu: [{0}]
UnsupportedImageBuild                   = Niewspierana Kompilacja Obrazu: [{0}]
SupportedImageBuild                     = Wspierana Kompilacja Obrazu: [{0}]
MountingImage                           = Montowanie {0}
FailedMountingImage                     = Nieudane Montowanie {0}: {1}
PreOptimizedImageHealthHealthy          = Stan Zdrowia Obrazu Przed-Optymalizacją: [Zdrowy]
PreOptimizedImageHealthCorrupted        = Ten obraz został oznaczony jako uszkodzony. Dalsze serwisowanie jest wymagane aby obraz mógł zostać zoptymalizowany.
RemovingWindowsApp                      = Usuwanie Pakietu Aprowizowanej Aplikacji: {0}
FailedRemovingWindowsApps               = Nieudane Usuwanie Pakietów Aprowizowanej Aplikacji: {0}
SystemAppsWarning                       = NIE usuwaj żadnej Aplikacji Systemowej jeżeli nie jesteś pewien jak zachowa się instalacja na żywo.
RemovingSystemApp                       = Usuwanie Systemowej Aplikacji: {0}
FailedRemovingSystemApp                 = Nieudane Usuwanie Systemowej Aplikacji: {0}
FailedRemovingSystemApps                = Nieudane Usuwanie Systemowych Aplikacji: {0}
RemovePackageCleanup                    = Wyłączenie Serwisów, Sterowników i Zintegrowanych Treści dla Usuniętych Aplikacji.
FailedRemovePackageCleanup              = Nieudane Wyłączenie Serwisów, Sterowników i Zintegrowanych Treści dla Usuniętych Aplikacji: {0}
DisablingDefenderOptionalFeature        = Wyłączenie Funkcji Opcjonalnej: Windows-Defender-Default-Definitions
ImportingCustomAppAssociations          = Importowanie Własnych Skojarzeń Typów Plików Aplikacji.
FailedImportingCustomAppAssociations    = Nieudane Importowanie Własnych Skojarzeń Typów Plików Aplikacji.
RemovingWindowsCapability               = Usuwanie Funkcji Windows: {0}
FailedRemovingWindowsCapabilities       = Nieudane Usuwanie Funkcji Windows: {0}
RemovingWindowsPackage                  = Usuwanie Pakietu Windows: {0}
FailedRemovingWindowsPackages           = Nieudane Usuwanie Pakietów Windows: {0}
DisablingUnsafeOptionalFeature          = Wyłączanie Niepewnej Funkcji Opcjonalnej: {0}
DisablingOptionalFeature                = Wyłączanie Funkcji Opcjonalnej: {0}
FailedDisablingOptionalFeatures         = Nieudane Wyłączanie Funkcji Opcjonalnych: {0}
EnablingOptionalFeature                 = Włączanie Funkcji Opcjonalnej: {0}
FailedEnablingOptionalFeatures          = Nieudane Włączanie Funkcji Opcjonalnych: {0}
IntegratingDeveloperMode                = Integracja Paczki Funkcji Trybu Deweloperskiego.
FailedIntegratingDeveloperMode          = Nieudana Integracja Paczki Funkcji Trybu Deweloperskiego.
IntegratingWindowsStore                 = Integracja Paczek Aplikacji Sklepu Windows.
FailedIntegratingWindowsStore           = Nieudana Integracja Paczek Aplikacji Sklepu Windows: {0}
IntegratingMicrosoftEdge                = Integracja Paczek Aplikacji Przeglądarka Microsoft Edge.
FailedIntegratingMicrosoftEdge          = Nieudana Integracja Paczek Aplikacji Przeglądarka Microsoft Edge: {0}
IntegratingWin32Calc                    = Integracja Kalkulatora Win32.
FailedIntegratingWin32Calc              = Nieudana Integracja Kalkulatora Win32: {0}
IntegratingDataDedup                    = Integracja Paczek De-duplikacji Danych.
FailedIntegratingDataDedup              = Nieudana Integracja Paczek De-duplikacji Danych: {0}
IntegratingDaRT10                       = Integracja Microsoft DaRT 10 i Narzędzia Debugowania Windows {0} do {1}
FailedIntegratingDaRT10                 = Nieudana Integracja Microsoft DaRT do {0}: {1}
ApplyingRegistrySettings                = Stosowanie Zoptymalizowanych Ustawień Rejestru.
ApplyingSetupContent                    = Stosowanie Zawartości Instalacji.
ApplyingWallpaper                       = Stosowanie Tapety.
ApplyingSystemLogo                      = Stosowanie Logo Systemowego.
ApplyingLockScreen                      = Stosowanie Ekranu Blokowania.
ImportingRegistryTemplates              = Importowanie Szablonów Rejestru.
ApplyingAnswerFile                      = Stosowanie Pliku Odpowiedzi.
FailedApplyingAnswerFile                = Nieudane Stosowanie Pliku Odpowiedzi: {0}
InjectingDriverPackages                 = Wstrzykiwanie Paczek Sterowników do {0}
FailedInjectingDriverPackages           = Nieudane Wstrzykiwanie Paczek Sterowników do {0}: {1}
EnablingNetFx3                          = Włączanie Funkcji Windows: NetFx3
FailedEnablingNetFx3                    = Nieudane Włączanie Funkcji Windows: NetFx3: {0}
CleanupStartMenu                        = Czyszczenie Ułożenia Menu Start.
CreatingPackageSummaryLog               = Tworzenie Dziennika Podsumowania Paczek.
PostOptimizedImageHealthHealthy         = Stan Zdrowia Obrazu Po-Optymalizacji: [Zdrowy]
PostOptimizedImageHealthCorrupted       = Ten obraz został oznaczony jako uszkodzony. Porzucanie Optymalizacji.
SavingDismountingImage                  = Zapisanie Zmian i Od-montowanie {0}
FailedSavingDismountingImage            = Nieudane Zapisanie Zmian i Od-montowanie {0}: {1}
RebuildingExportingImage                = Odbudowywanie i Eksportowanie {0}
FailedRebuildingExportingImage          = Nieudane Odbudowywanie i Eksportowanie {0}: {1}
SolidCompressionWarning                 = Kompresja plików współdzielonych może zająć trochę czasu. Proszę o cierpliwość, aż się zakończy.
RebuildingExportingCompressed           = Odbudowywanie i Eksportowanie {0} używając  kompresji {1}.
FailedRebuildingExportingSolid          = Nieudane Odbudowywanie i Eksportowanie {0} używając kompresji {1}.
FailedRebuildingExportingCompressed     = Nieudane Odbudowywanie i Eksportowanie {0} używając {1} kompresji: {2}
OptimizingWindowsMedia                  = Optymalizacja Struktury Plików Windows Media.
CreatingISO                             = Tworzenie {0} ISO Rozruchowej Instalacji Systemu Windows.
FinalizingOptimizations                 = Finalizowanie Optymalizacji.
OptimizationsCompleted                  = {0} ukończono w [{1}] minut mając [{2}] błędów.
'@